
export const FETCH_BOOK_START='FETCH_BOOK_START';
export const FETCH_BOOK_SUCCESS='FETCH_BOOK_SUCCESS';
export const FETCH_BOOK_FAIL='FETCH_BOOK_FAIL';
export const FETCH_BOOK_CLEAR = 'FETCH_BOOK_CLEAR';

export const NEW_BOOK_START='NEW_BOOK_START';
export const NEW_BOOK_SUCCESS='NEW_BOOK_SUCCESS';
export const NEW_BOOK_FAIL='NEW_BOOK_FAIL';
export const NEW_BOOK_CLEAR = 'NEW_BOOK_CLEAR';

